### ISSUE TITLE
HTTP Operation failed. Inspect status code for details

### ISSUE THREAD

**Issue by vladimirnani** [smarttradeapp/django_cbtools#27]
I get this error when invoking `query_objects`.
All tests run with success except `test_query_objects`. Also in my app if i invoke `query_objects` i get same error.
```

Error
Traceback (most recent call last):
  File "\lib\site-packages\django_cbtools\tests.py", line 644, in test_query_objects
    query_objects('by_channel', key, Mock)
  File "\lib\site-packages\django_cbtools\models.py", line 340, in query_objects
    result = query_view(view_name, query_key=query_key, query=query)
  File "\lib\site-packages\django_cbtools\models.py", line 335, in query_view
    result_keys = [x.docid for x in result]
  File "\lib\site-packages\couchbase-2.0.8-py2.7-win-amd64.egg\couchbase\views\iterator.py", line 399, in __iter__
    raw_rows = self.raw.fetch(self._mres)
HTTPError: <RC=0x3B[HTTP Operation failed. Inspect status code for details], HTTP Request failed. Examine 'objextra' for full result, Results=1, C Source=(src\http.c,140), OBJ=ViewResult<rc=0x3B[HTTP Operation failed. Inspect status code for details], value=None, http_status=404>>


```

**Comment by vladimirnani** [comment]
Solved by copying couchbase_views into package folder. I think it should be there by default.

**Comment by iutinvg** [comment]
indeed. thank you for informing!
